/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package datagen.example;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class transactions extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3681760270873077378L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"transactions\",\"namespace\":\"datagen.example\",\"fields\":[{\"name\":\"transaction_id\",\"type\":\"long\"},{\"name\":\"card_id\",\"type\":\"long\"},{\"name\":\"user_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"purchase_id\",\"type\":\"long\"},{\"name\":\"store_id\",\"type\":\"int\"}],\"connect.name\":\"datagen.example.transactions\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<transactions> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<transactions> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<transactions> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<transactions> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<transactions> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this transactions to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a transactions from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a transactions instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static transactions fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long transaction_id;
  private long card_id;
  private java.lang.String user_id;
  private long purchase_id;
  private int store_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public transactions() {}

  /**
   * All-args constructor.
   * @param transaction_id The new value for transaction_id
   * @param card_id The new value for card_id
   * @param user_id The new value for user_id
   * @param purchase_id The new value for purchase_id
   * @param store_id The new value for store_id
   */
  public transactions(java.lang.Long transaction_id, java.lang.Long card_id, java.lang.String user_id, java.lang.Long purchase_id, java.lang.Integer store_id) {
    this.transaction_id = transaction_id;
    this.card_id = card_id;
    this.user_id = user_id;
    this.purchase_id = purchase_id;
    this.store_id = store_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transaction_id;
    case 1: return card_id;
    case 2: return user_id;
    case 3: return purchase_id;
    case 4: return store_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transaction_id = (java.lang.Long)value$; break;
    case 1: card_id = (java.lang.Long)value$; break;
    case 2: user_id = value$ != null ? value$.toString() : null; break;
    case 3: purchase_id = (java.lang.Long)value$; break;
    case 4: store_id = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transaction_id' field.
   * @return The value of the 'transaction_id' field.
   */
  public long getTransactionId() {
    return transaction_id;
  }


  /**
   * Sets the value of the 'transaction_id' field.
   * @param value the value to set.
   */
  public void setTransactionId(long value) {
    this.transaction_id = value;
  }

  /**
   * Gets the value of the 'card_id' field.
   * @return The value of the 'card_id' field.
   */
  public long getCardId() {
    return card_id;
  }


  /**
   * Sets the value of the 'card_id' field.
   * @param value the value to set.
   */
  public void setCardId(long value) {
    this.card_id = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.String getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'purchase_id' field.
   * @return The value of the 'purchase_id' field.
   */
  public long getPurchaseId() {
    return purchase_id;
  }


  /**
   * Sets the value of the 'purchase_id' field.
   * @param value the value to set.
   */
  public void setPurchaseId(long value) {
    this.purchase_id = value;
  }

  /**
   * Gets the value of the 'store_id' field.
   * @return The value of the 'store_id' field.
   */
  public int getStoreId() {
    return store_id;
  }


  /**
   * Sets the value of the 'store_id' field.
   * @param value the value to set.
   */
  public void setStoreId(int value) {
    this.store_id = value;
  }

  /**
   * Creates a new transactions RecordBuilder.
   * @return A new transactions RecordBuilder
   */
  public static datagen.example.transactions.Builder newBuilder() {
    return new datagen.example.transactions.Builder();
  }

  /**
   * Creates a new transactions RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new transactions RecordBuilder
   */
  public static datagen.example.transactions.Builder newBuilder(datagen.example.transactions.Builder other) {
    if (other == null) {
      return new datagen.example.transactions.Builder();
    } else {
      return new datagen.example.transactions.Builder(other);
    }
  }

  /**
   * Creates a new transactions RecordBuilder by copying an existing transactions instance.
   * @param other The existing instance to copy.
   * @return A new transactions RecordBuilder
   */
  public static datagen.example.transactions.Builder newBuilder(datagen.example.transactions other) {
    if (other == null) {
      return new datagen.example.transactions.Builder();
    } else {
      return new datagen.example.transactions.Builder(other);
    }
  }

  /**
   * RecordBuilder for transactions instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<transactions>
    implements org.apache.avro.data.RecordBuilder<transactions> {

    private long transaction_id;
    private long card_id;
    private java.lang.String user_id;
    private long purchase_id;
    private int store_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(datagen.example.transactions.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[0].schema(), other.transaction_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.card_id)) {
        this.card_id = data().deepCopy(fields()[1].schema(), other.card_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.user_id)) {
        this.user_id = data().deepCopy(fields()[2].schema(), other.user_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.purchase_id)) {
        this.purchase_id = data().deepCopy(fields()[3].schema(), other.purchase_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.store_id)) {
        this.store_id = data().deepCopy(fields()[4].schema(), other.store_id);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing transactions instance
     * @param other The existing instance to copy.
     */
    private Builder(datagen.example.transactions other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[0].schema(), other.transaction_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.card_id)) {
        this.card_id = data().deepCopy(fields()[1].schema(), other.card_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.user_id)) {
        this.user_id = data().deepCopy(fields()[2].schema(), other.user_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.purchase_id)) {
        this.purchase_id = data().deepCopy(fields()[3].schema(), other.purchase_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.store_id)) {
        this.store_id = data().deepCopy(fields()[4].schema(), other.store_id);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'transaction_id' field.
      * @return The value.
      */
    public long getTransactionId() {
      return transaction_id;
    }


    /**
      * Sets the value of the 'transaction_id' field.
      * @param value The value of 'transaction_id'.
      * @return This builder.
      */
    public datagen.example.transactions.Builder setTransactionId(long value) {
      validate(fields()[0], value);
      this.transaction_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_id' field has been set.
      * @return True if the 'transaction_id' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transaction_id' field.
      * @return This builder.
      */
    public datagen.example.transactions.Builder clearTransactionId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'card_id' field.
      * @return The value.
      */
    public long getCardId() {
      return card_id;
    }


    /**
      * Sets the value of the 'card_id' field.
      * @param value The value of 'card_id'.
      * @return This builder.
      */
    public datagen.example.transactions.Builder setCardId(long value) {
      validate(fields()[1], value);
      this.card_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'card_id' field has been set.
      * @return True if the 'card_id' field has been set, false otherwise.
      */
    public boolean hasCardId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'card_id' field.
      * @return This builder.
      */
    public datagen.example.transactions.Builder clearCardId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public datagen.example.transactions.Builder setUserId(java.lang.String value) {
      validate(fields()[2], value);
      this.user_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public datagen.example.transactions.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'purchase_id' field.
      * @return The value.
      */
    public long getPurchaseId() {
      return purchase_id;
    }


    /**
      * Sets the value of the 'purchase_id' field.
      * @param value The value of 'purchase_id'.
      * @return This builder.
      */
    public datagen.example.transactions.Builder setPurchaseId(long value) {
      validate(fields()[3], value);
      this.purchase_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'purchase_id' field has been set.
      * @return True if the 'purchase_id' field has been set, false otherwise.
      */
    public boolean hasPurchaseId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'purchase_id' field.
      * @return This builder.
      */
    public datagen.example.transactions.Builder clearPurchaseId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'store_id' field.
      * @return The value.
      */
    public int getStoreId() {
      return store_id;
    }


    /**
      * Sets the value of the 'store_id' field.
      * @param value The value of 'store_id'.
      * @return This builder.
      */
    public datagen.example.transactions.Builder setStoreId(int value) {
      validate(fields()[4], value);
      this.store_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'store_id' field has been set.
      * @return True if the 'store_id' field has been set, false otherwise.
      */
    public boolean hasStoreId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'store_id' field.
      * @return This builder.
      */
    public datagen.example.transactions.Builder clearStoreId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public transactions build() {
      try {
        transactions record = new transactions();
        record.transaction_id = fieldSetFlags()[0] ? this.transaction_id : (java.lang.Long) defaultValue(fields()[0]);
        record.card_id = fieldSetFlags()[1] ? this.card_id : (java.lang.Long) defaultValue(fields()[1]);
        record.user_id = fieldSetFlags()[2] ? this.user_id : (java.lang.String) defaultValue(fields()[2]);
        record.purchase_id = fieldSetFlags()[3] ? this.purchase_id : (java.lang.Long) defaultValue(fields()[3]);
        record.store_id = fieldSetFlags()[4] ? this.store_id : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<transactions>
    WRITER$ = (org.apache.avro.io.DatumWriter<transactions>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<transactions>
    READER$ = (org.apache.avro.io.DatumReader<transactions>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.transaction_id);

    out.writeLong(this.card_id);

    out.writeString(this.user_id);

    out.writeLong(this.purchase_id);

    out.writeInt(this.store_id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.transaction_id = in.readLong();

      this.card_id = in.readLong();

      this.user_id = in.readString();

      this.purchase_id = in.readLong();

      this.store_id = in.readInt();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.transaction_id = in.readLong();
          break;

        case 1:
          this.card_id = in.readLong();
          break;

        case 2:
          this.user_id = in.readString();
          break;

        case 3:
          this.purchase_id = in.readLong();
          break;

        case 4:
          this.store_id = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










